export const VERSES = [
    { text: "Rabbinizin hangi nimetlerini yalanlayabilirsiniz?", source: "Rahman Suresi, 13" },
    { text: "Şüphesiz, zorlukla beraber bir kolaylık vardır.", source: "İnşirah Suresi, 5" },
    { text: "Eğer şükrederseniz, elbette size (nimetimi) artırırım.", source: "İbrahim Suresi, 7" },
    { text: "Allah, sabredenlerle beraberdir.", source: "Bakara Suresi, 153" },
    { text: "Bilsinler ki, kalpler ancak Allah'ı anmakla huzur bulur.", source: "Ra'd Suresi, 28" },
    { text: "Rabbimiz! Bize dünyada da iyilik ver, ahirette de iyilik ver.", source: "Bakara Suresi, 201" },
    { text: "Allah yükümlülük teklif etmez, ancak gücünün yettiği kadarını.", source: "Bakara Suresi, 286" },
    { text: "O, kullarının tövbesini kabul eden, kötülükleri bağışlayandır.", source: "Şura Suresi, 25" },
    { text: "De ki: Rabbim ilmimi artır.", source: "Taha Suresi, 114" },
    { text: "Şüphesiz Allah, tevekkül edenleri sever.", source: "Al-i İmran Suresi, 159" },
    { text: "İyilik, yüzlerinizi doğu ve batı tarafına çevirmeniz değildir.", source: "Bakara Suresi, 177" },
    { text: "Yeryüzünde böbürlenerek yürüme.", source: "İsra Suresi, 37" },
    { text: "Allah size kolaylık diler, zorluk dilemez.", source: "Bakara Suresi, 185" },
    { text: "Müminler ancak kardeştirler.", source: "Hucurat Suresi, 10" },
    { text: "Hiç bilenlerle bilmeyenler bir olur mu?", source: "Zümer Suresi, 9" },
    { text: "Allah, adaletli olanları sever.", source: "Maide Suresi, 42" },
    { text: "Her nefis ölümü tadacaktır.", source: "Al-i İmran Suresi, 185" },
    { text: "Biz insanı en güzel biçimde yarattık.", source: "Tin Suresi, 4" },
    { text: "Rabbin seni terk etmedi ve sana darılmadı.", source: "Duha Suresi, 3" },
    { text: "O, her şeyi hakkıyla işitendir, hakkıyla bilendir.", source: "Enam Suresi, 13" },
    { text: "Göklerde ve yerde ne varsa O'nundur.", source: "Bakara Suresi, 255" },
    { text: "Şüphesiz Allah, işiten ve görendir.", source: "Hac Suresi, 75" },
    { text: "Rabbim! Bağışla ve merhamet et. Sen merhamet edenlerin en hayırlısısın.", source: "Müminun Suresi, 118" },
    { text: "Şüphe yok ki Allah, sabredenleri sever.", source: "Al-i İmran Suresi, 146" },
    { text: "Allah kullarına karşı çok şefkatlidir.", source: "Bakara Suresi, 207" },
    { text: "Size verilen şey, dünya hayatının geçimine aittir.", source: "Şura Suresi, 36" },
    { text: "Allah'ın rahmetinden ümidinizi kesmeyin.", source: "Zümer Suresi, 53" },
    { text: "Ancak sana kulluk eder ve ancak senden yardım dileriz.", source: "Fatiha Suresi, 5" },
    { text: "Andolsun, biz insanı bir meşakkat içinde yarattık.", source: "Beled Suresi, 4" },
    { text: "Kim zerre miktarı hayır yapmışsa onu görür.", source: "Zilzal Suresi, 7" }
];
